### PR TITLE
fix rancheros docker engine switch

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I've also made https://github.com/docker/docker-install/pull/7

hopefully that'll simplify things

**Comment by SvenDowideit** [comment]
@vincent99

**Comment by vincent99** [comment]
No 17.04/05 or 1.12.x (which is still the default for Rancher because k8s)?

**Comment by superseb** [comment]
1.12 wasn't changed so rancheros is still in there, and I already updated the PR for 17.04/17.05.

**Pull request merged**
