### PR TITLE
Add 23.0.2 version and fix some link issues

### PR DESCRIPTION
**Pull request by mitulshah-suse**
Related to https://github.com/rancher/rancher/issues/40731

### CODE REVIEW

**Comment by mitulshah-suse** [comment]
@snasovich Thanks for the approval. We dont have privs ot merge PRs in this repo, so can you please merge the PR as well.

**Comment by snasovich** [comment]
> @snasovich @superseb Thanks for the approval. We dont have privs ot merge PRs in this repo, so can you please merge the PR as well.

@mitulshah-suse , I don't see @superseb 's approval yet, so let's wait for +1 approval.

@superseb @kinarashah , wondering if you could review and hopefully approve?

**Review by kinarashah — COMMENTED** [review]
@mitulshah-suse I am curious on why we are updating `dist/20.10.sh` again when it already seems to be at `20.10.23.sh` at the latest commit, is there something I'm missing? Other changes look good to me.

**Comment by mitulshah-suse** [comment]
> @mitulshah-suse I am curious on why we are updating `dist/20.10.sh` again when it already seems to be at `20.10.23.sh` at the latest commit, is there something I'm missing? Other changes look good to me.

The `dist/20.10.sh` link was still pointing to `20.10.21.sh`. There was a mistake in the previous commit, the link pointing to `20.10.23.sh` was created in the wrong folder. So fixed that error in this PR.

**Comment by kinarashah** [comment]
@mitulshah-suse makes sense. Could you add validation check in CI so we don't miss this in future? This is to ensure all links for `dist/$major.$minor.$sh` always point to the latest `$major.$minor.$patch.sh`. It will avoid confusion and take care of issues like https://github.com/rancher/rancher/issues/40469#issuecomment-1497650935. I'm okay if you want to create a new issue and PR for it.

**Comment by mitulshah-suse** [comment]
> @mitulshah-suse makes sense. Could you add validation check in CI so we don't miss this in future? This is to ensure all links for `dist/$major.$minor.$sh` always point to the latest `$major.$minor.$patch.sh`. It will avoid confusion and take care of issues like [rancher/rancher#40469 (comment)](https://github.com/rancher/rancher/issues/40469#issuecomment-1497650935). I'm okay if you want to create a new issue and PR for it.

@kinarashah Have raised a separate [issue](https://github.com/rancher/rancher/issues/41096) and PR for that. Will track the link checker from there.

**Review by kinarashah — APPROVED** [review]

**Pull request merged**
