### PR TITLE
switch Docker engine to the requested version

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

looks like I need to get a fix into docker-machine to use the `engine-install-url` if present

### CODE REVIEW

**Comment by SvenDowideit** [comment]
and to go with it, https://github.com/docker/machine/pull/4082

**Comment by SvenDowideit** [comment]
@vincent99 ?

**Comment by vincent99** [comment]
Seems fine to me but it's there any point merging until docker-machine accepts your other PR (or we start maintaining it as a patch)?

**Comment by vincent99** [comment]
Why sleep and why 3?

**Comment by SvenDowideit** [comment]
the `sleep 3` is copied from the other entries - its what docker have. personally, I think we should remove the `sleep 20` from the script too

**Comment by SvenDowideit** [comment]
may as well merge now - that'll give us the option to carry a patched version of machine if it doesn't get merged sooner.

**Pull request merged**
