### PR TITLE
Fix 20.10.sh to properly install on oracle linux 7

### PR DESCRIPTION
**Pull request by rawmind0**
Issue https://github.com/rancher/rancher/issues/31132

### CODE REVIEW

**Review by superseb — CHANGES_REQUESTED** [review]
In `19.03`, this is done using:

```
                                if [ "$lsb_dist" = "oraclelinux" ]; then
                                        case $dist_version in
                                                7*)
                                                        for ol_repo in $ol_repos ; do
                                                                $sh_c "$config_manager $enable_channel_flag $ol_repo"
                                                        done
                                                        ;;
                                        esac
                                fi
```

Why is this different (approach but also `lsb_dist`)/adding another repository? Or did something change on the OEL side?

**Comment by rawmind0** [comment]
It seems something changed on the OEL 7 side, about 20.10 docker package dependencies. For docker 20.10, OEL is asking for:
* container-selinux >= 2:2.74: Same than 19.03, available at `ol7_addons` repo
* slirp4netns >= 0.4: New one, available at OEL developer repo, `https://yum.oracle.com/repo/OracleLinux/OL7/developer/x86_64`
* fuse-overlayfs >= 0.7: New one, available at OEL developer repo, `https://yum.oracle.com/repo/OracleLinux/OL7/developer/x86_64`

Not adding OEL 7 developer repo is making installation script fails, https://github.com/rancher/rancher/issues/31132#issuecomment-777085041

**Review by superseb — DISMISSED** [review]

**Comment by superseb** [comment]
```Loaded plugins: ovl
adding repo from: https://yum.oracle.com/repo/OracleLinux/OL7/developer/x86_64
Cannot add repo from https://yum.oracle.com/repo/OracleLinux/OL7/developer/x86_64 as is a duplicate of an existing repo```

This needs to be fixed if it already exists.

**Comment by rawmind0** [comment]
@superseb , added the fix you mentioned and added oracle linux 7 and 8 to the dind tests

**Review by superseb — APPROVED** [review]

**Pull request merged**
